physics:
  flow:
    mode: swe
    well_balancing: hydrostatic_reconstruction
    h_anuga_reg_parameter: 0.01

numerics:
  spatial: fv
  temporal: euler
  riemann: roe

logging:
  level: debug

time:
  stop             : 691200.0 # 8 days
  coupling_interval: 3600.0   # 60 mins
  time_step        : 0.5
  unit             : seconds

output:
  fields:
    - Height
    - MomentumX
    - MomentumY
  format: xdmf
  output_interval: 7200       # 1-hr (=36000 * 0.1 sec = 3600 sec)
  batch_size: 60               # 24 time slices put in a single .h5
  time_series:
    boundary_fluxes: 7200

grid:
  file: Turning_30_90_1500_1000.exo

regions:
  - name: domain
    grid_region_id: 1

surface_composition:
  - region: domain
    material: smooth

materials:
  - name: smooth
    properties:
      manning:
        value: 0.015

initial_conditions:
  - region: domain
    flow: domain_flow_ic

boundaries:
  - name: outlet
    grid_boundary_id: 1

boundary_conditions:
  - boundaries: [outlet]
    flow: tidal_bc

flow_conditions:
  - name: domain_flow_ic
    type: dirichlet
    file: Turning_30_90_1500_1000_IC0.bin
    format: binary
  - name: tidal_bc
    type: dirichlet
    height: 0
    x_momentum: 0
    y_momentum: 0
